Update patch set 6
Patch Set 6:

Fails with 

INFO: Found 1 target...
ERROR: /Users/patrickmulhall/Documents/workspace/gerrit/plugins/delete-project/BUILD:9:1: Building plugins/delete-project/libdelete-project__plugin-class.jar (17 source files) failed (Exit 1).
plugins/delete-project/src/main/java/com/googlesource/gerrit/plugins/deleteproject/DeleteCommand.java:59: error: incompatible types: ProjectState cannot be converted to ProjectResource
      ProjectResource rsrc = new ProjectResource(projectState);

(Only 1 error now instead of mutiple's)

Patch-set: 6
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>