Update patch set 34
Patch Set 34:

It seems that the merged version again provokes this error on PG on every page load (YOUR > Changes for instance):

  Plugin install error: TypeError: self.onAction is not a function

This was no longer happening with some of the intermediate patchsets - around 25 or so?

Patch-set: 34