Update patch set 5
Patch Set 5:

> Does not compile in standalone. Fails with this error:
 > 
 > INFO: Found 7 targets...
 > ERROR: /home/ehecabo/gerrit_plugins/delete-project/BUILD:21:1:
 > Building delete_project_tests.jar (6 source files) failed (Exit 1)
 > src/test/java/com/googlesource/gerrit/plugins/deleteproject/DeleteProjectIT.java:37:
 > error: package com.google.gwt.thirdparty.json does not exist
 > import com.google.gwt.thirdparty.json.JSONObject;
 > ^
 > src/test/java/com/googlesource/gerrit/plugins/deleteproject/DeleteProjectIT.java:100:
 > error: cannot find symbol
 > RestResponse r = adminRestSession.post(endPoint, new
 > JSONObject().put("force", "true"));
 > ^
 > symbol:   class JSONObject
 > location: class DeleteProjectIT
 > src/test/java/com/googlesource/gerrit/plugins/deleteproject/DeleteProjectIT.java:117:
 > error: cannot find symbol
 > RestResponse r = adminRestSession.post(endPoint, new
 > JSONObject().put("force", "true"));
 > ^
 > symbol:   class JSONObject
 > location: class DeleteProjectIT
 > INFO: Elapsed time: 1.243s, Critical Path: 0.95s
 > FAILED: Build did NOT complete successfully

Removed gwt.thirdparty.json.JSONObject library which was in the change I26210d105bb4564a85a60f0fb8e6361a97560e3c

Patch-set: 5
Reviewer: Borui Tao <1060002@173816e5-2b9a-37c3-8a2e-48639d4f1153>