Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> I'm unable to pass the plugin tests starting with this change, locally. I think I did rebuild and reinstall the (latest) 2.16 /snapshot api properly. -Are you able to? Here is what I'm getting:
> 
> (...)
> Caused by: java.lang.NoSuchMethodError: com.google.gerrit.httpd.HttpLogoutServlet.<init>(Lcom/google/gerrit/server/config/AuthConfig;Lcom/google/gerrit/extensions/registration/DynamicItem;Lcom/google/inject/Provider;Lcom/google/gerrit/server/group/GroupAuditService;)V
>         at com.google.gerrit.httpd.auth.openid.OAuthOverOpenIDLogoutServlet.<init>(OAuthOverOpenIDLogoutServlet.java:44)
>         at com.google.gerrit.httpd.auth.openid.OAuthOverOpenIDLogoutServlet$$FastClassByGuice$$83c738fd.newInstance(<generated>)
>         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
>         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
>         ... 36 more

If you have previously built the snapshot, you will also need to remove it from bazel's cache so that it actually uses the newly built one instead of the cached one.

Patch-set: 1