Update patch set 2
Patch Set 2: Verified-1

Build fails for me with:
/usr/src/tmp/gerrit/plugins/delete-project/src/main/java/com/googlesource/gerrit/plugins/deleteproject/fs/DeleteTrashFolders.java:72: error: method addAll in class java.util.Collections cannot be applied to given types;
    Collections.addAll(repoFolders, repositoryCfg.getAllBasePaths());
               ^
  required: java.util.Collection<? super T>,T[]
  found: java.util.Set<java.lang.String>,java.util.List<java.nio.file.Path>
  reason: inferred type does not conform to upper bound(s)
    inferred: java.util.List<java.nio.file.Path>
    upper bound(s): java.lang.String,java.lang.Object
Errors: 1. Warnings: 0.

Patch-set: 2
Label: Verified=-1