Fix JavaTimeDefaultTimeZone error flagged by error prone
Running recent error prone version complaining on that code:

TimeMachine.java:54: error: [JavaTimeDefaultTimeZone] Clock.systemDefaultZone()
is not allowed because it silently uses the system default time-zone.
You must pass an explicit time-zone (e.g., ZoneId.of("America/Los_Angeles")
 to this method.
    clock = Clock.systemDefaultZone();
                                   ^
    (see https://errorprone.info/bugpattern/JavaTimeDefaultTimeZone)

Change-Id: I10e34bf90d1903aeb40810509b87b0519971ade1