Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > I wanted to give V+1 but when I was calling
> > bazel test //...
> > in plugin/delete-project I got the following which I believe is unrelated:
> > 
> > JUnit4 Test Runner
> > ...............log4j:WARN No appenders could be found for logger (org.eclipse.jgit.util.FS).
> > log4j:WARN Please initialize the log4j system properly.
> > log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> > E......
> > Time: 1.255
> > There was 1 failure:
> > 1) testStart(com.googlesource.gerrit.plugins.deleteproject.fs.DeleteTrashFoldersTest)
> > java.lang.AssertionError: The subject was expected to be false, but was true
> > 	at com.googlesource.gerrit.plugins.deleteproject.fs.DeleteTrashFoldersTest.testStart(DeleteTrashFoldersTest.java:63)
> > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > 	at java.lang.reflect.Method.invoke(Method.java:498)
> > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
> > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
> > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> > 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
> > 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
> > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
> > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> > 	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
> > 	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
> > 	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
> > 	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
> > 	at org.junit.runners.Suite.runChild(Suite.java:127)
> > 	at org.junit.runners.Suite.runChild(Suite.java:26)
> > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> > 	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
> > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
> > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
> > 	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
> > 	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
> > 	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
> > Caused by: java.lang.AssertionError: The subject was expected to be false, but was true
> > 	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
> > 	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
> > 	at com.google.common.truth.Subject.failWithRawMessage(Subject.java:438)
> > 	at com.google.common.truth.BooleanSubject.isFalse(BooleanSubject.java:44)
> > 	... 39 more
> > 
> > Which might be related to this one (found in eclipse while debugging the test in question):
> > 
> > [2018-09-18 15:23:01,351] [DeleteTrashFolders] ERROR com.googlesource.gerrit.plugins.deleteproject.fs.DeleteTrashFolders : Failed to delete /var/folders/46/31kwj_356_n240954hk9ldl00000gn/T/junit1659838929987503612/gerrit_site/base/repo.1234567890123.deleted
> > com.google.common.io.InsecureRecursiveDeleteException: /var/folders/46/31kwj_356_n240954hk9ldl00000gn/T/junit1659838929987503612/gerrit_site/base/repo.1234567890123.deleted: unable to guarantee security of recursive delete
> > 	at com.google.common.io.MoreFiles.checkAllowsInsecure(MoreFiles.java:739)
> > 	at com.google.common.io.MoreFiles.deleteRecursively(MoreFiles.java:525)
> > 	at com.googlesource.gerrit.plugins.deleteproject.fs.DeleteTrashFolders.recursivelyDelete(DeleteTrashFolders.java:102)
> > 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> > 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> > 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> > 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> > 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> > 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> > 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> > 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> > 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> > 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> > 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> > 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> > 	at com.googlesource.gerrit.plugins.deleteproject.fs.DeleteTrashFolders.evaluateIfTrash(DeleteTrashFolders.java:89)
> > 	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
> > 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> > 	at com.googlesource.gerrit.plugins.deleteproject.fs.DeleteTrashFolders.lambda$0(DeleteTrashFolders.java:81)
> > 	at java.lang.Thread.run(Thread.java:748)
> 
> Strange... If I run in Eclipse it passes and also when using bazel:
> 
> ehecabo@elxa8w3dxz1:~/gerrit_plugins/delete-project (stable-2.14=) $ bazel test //...
> Starting local Bazel server and connecting to it...
> INFO: Analysed target //:delete_project_tests (29 packages loaded).
> INFO: Found 1 test target...
> Target //:delete_project_tests up-to-date:
>   bazel-bin/delete_project_tests.jar
>   bazel-bin/delete_project_tests
> INFO: Elapsed time: 13.652s, Critical Path: 7.81s
> INFO: 5 processes: 3 linux-sandbox, 2 worker.
> INFO: Build completed successfully, 7 total actions
> //:delete_project_tests                                                  PASSED in 1.8s
> 
> Executed 1 out of 1 test: 1 test passes.
> INFO: Build completed successfully, 7 total actions

Probably we need to use the RecursiveDeleteOption.ALLOW_INSECURE when using Guava's  MoreFiles.deleteRecursively as Davido suggested in one of the previous changes. I didn't add it because I wasn't sure about the result in non-Unix filesystems but it seems we could need it. Could you please add locally this option and re-run the test to see if it fixes the issue?

Patch-set: 1
Reviewer: Gerrit User 1019328 <1019328@173816e5-2b9a-37c3-8a2e-48639d4f1153>