Add RecursiveDeleteOption.ALLOW_INSECURE for recursive deletion
Otherwise unit tests are failing on osx with the following error:
JUnit4 Test Runner
...............log4j:WARN No appenders could be found for logger
  (org.eclipse.jgit.util.FS).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig
  for more info.
E......
Time: 1.255
There was 1 failure:
1) testStart(com.googlesource.gerrit.plugins.deleteproject.fs
  .DeleteTrashFoldersTest)
java.lang.AssertionError: The subject was expected to be false,
  but was true
    at com.googlesource.gerrit.plugins.deleteproject.fs
      .DeleteTrashFoldersTest.testStart(DeleteTrashFoldersTest.java:63)
      ...

which is caused by:
[2018-09-18 15:23:01,351] [DeleteTrashFolders] ERROR com.googlesource.gerrit
    .plugins.deleteproject.fs.DeleteTrashFolders :
  Failed to delete /.../repo.1234567890123.deleted
  com.google.common.io.InsecureRecursiveDeleteException:
    /.../repo.1234567890123.deleted:
    unable to guarantee security of recursive delete
    at com.google.common.io.MoreFiles
      .checkAllowsInsecure(MoreFiles.java:739)
    at com.google.common.io.MoreFiles
      .deleteRecursively(MoreFiles.java:525)
    at com.googlesource.gerrit.plugins.deleteproject.fs
      .DeleteTrashFolders
        .recursivelyDelete(DeleteTrashFolders.java:102)

Change-Id: Ic0894b88e912ef538796f6817065d974b28bc0a4
Signed-off-by: Jacek Centkowski <jcentkowski@collab.net>